development: &default
  adapter: mysql2
  encoding: utf8mb4
  username: <%= ENV.fetch("MYSQL_USERNAME") { "root" } %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { "admin" } %>
  host: <%= ENV.fetch("MYSQL_HOST") { "127.0.0.1" } %>
  port: <%= ENV.fetch("MYSQL_PORT") { 3306 } %>
  timeout: 5000
  reconnect: <%= ENV.fetch("MYSQL_RECONNECT", true) == "true" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("DEBUG_PRODUCTION", "0") == "1" ? "test_rb" : "test_rb_development" %>

test:
  <<: *default
  database: test_rb_test

production:
  <<: *default
  database: test_rb_development
